/**
 * R2 Report Storage Logic (P8-S15)
 *
 * Shared logic for report generation and R2 storage.
 * Used by both the edge worker and tests.
 *
 * Reports are stored in the ARKOVA_REPORTS R2 bucket.
 * Signed URLs provide zero-egress downloads.
 * No PII in generated reports (Constitution 1.4).
 */

export interface ReportRequest {
  orgId: string;
  reportType: 'portfolio' | 'integrity' | 'trend';
  data: PortfolioData;
}

export interface PortfolioData {
  totalCredentials: number;
  byType: Record<string, number>;
  integrityDistribution: { high: number; medium: number; low: number };
}

/**
 * Build the R2 object key for a report.
 * Format: reports/{orgId}/{reportType}/{timestamp}.pdf
 *
 * Sanitizes orgId to prevent path traversal attacks.
 */
export function buildR2Key(orgId: string, reportType: string, timestamp: Date): string {
  // Sanitize orgId — strip path traversal characters
  const safeOrgId = orgId.replace(/[^a-zA-Z0-9_-]/g, '_');
  const safeType = reportType.replace(/[^a-zA-Z0-9_-]/g, '_');

  return `reports/${safeOrgId}/${safeType}/${timestamp.toISOString()}.pdf`;
}

/**
 * Generate markdown report content from portfolio data.
 *
 * Constitution 1.4: No PII in report output.
 * Reports contain only aggregate statistics and anonymized metadata.
 */
export function generateReportContent(request: ReportRequest): string {
  const { data } = request;

  const typeBreakdown = Object.entries(data.byType)
    .map(([type, count]) => `- **${type}:** ${count}`)
    .join('\n');

  const integrityBreakdown = [
    `- High (80+): ${data.integrityDistribution.high}`,
    `- Medium (50-79): ${data.integrityDistribution.medium}`,
    `- Low (<50): ${data.integrityDistribution.low}`,
  ].join('\n');

  return `# Portfolio Summary Report

**Generated:** ${new Date().toISOString()}
**Report Type:** ${request.reportType}

## Overview

**Total Credentials:** ${data.totalCredentials}

## Credential Types

${typeBreakdown}

## Integrity Distribution

${integrityBreakdown}

---
_Generated by Arkova AI. No personally identifiable information included._
`;
}

/**
 * Generate a signed URL for zero-egress R2 download.
 *
 * Uses R2's built-in presigned URL support.
 * Default expiry: 1 hour.
 */
export function generateSignedUrlParams(key: string, expiresInSeconds = 3600): {
  key: string;
  expiresIn: number;
} {
  return { key, expiresIn: expiresInSeconds };
}
